// ============================================================
// NeuralLang Transpiler — Main API
// Menghubungkan Lexer → Parser → Code Generator
// ============================================================

import { Lexer } from './lexer';
import { Parser } from './parser';
import { CodeGenerator } from './codegen';

export interface TranspileResult {
  success: boolean;
  python: string;
  imports: string[];
  errors: string[];
  warnings: string[];
  stats: {
    inputLines: number;
    outputLines: number;
    reduction: string;
    compileTime: number;
  };
}

export interface TranspileOptions {
  includeImports?: boolean;
  includeComments?: boolean;
}

export function transpile(
  source: string,
  options: TranspileOptions = {}
): TranspileResult {
  const {
    includeImports = true,
    includeComments = true,
  } = options;

  const startTime = performance.now();
  const errors: string[] = [];
  const warnings: string[] = [];

  // 1. Lexing
  const lexer = new Lexer(source);
  let tokens;
  try {
    tokens = lexer.tokenize();
  } catch (e: any) {
    return {
      success: false,
      python: '',
      imports: [],
      errors: [`Lexer error: ${e.message}`],
      warnings: [],
      stats: { inputLines: 0, outputLines: 0, reduction: '0%', compileTime: 0 },
    };
  }

  // 2. Parsing
  const parser = new Parser(tokens);
  let ast;
  try {
    ast = parser.parse();
  } catch (e: any) {
    return {
      success: false,
      python: '',
      imports: [],
      errors: [`Parse error: ${e.message}`],
      warnings: [],
      stats: { inputLines: source.split('\n').length, outputLines: 0, reduction: '0%', compileTime: performance.now() - startTime },
    };
  }

  // 3. Code Generation
  const codegen = new CodeGenerator();
  let rawCode;
  try {
    const result = codegen.generate(ast);
    rawCode = result.code;
  } catch (e: any) {
    return {
      success: false,
      python: '',
      imports: [],
      errors: [`Code generation error: ${e.message}`],
      warnings: [],
      stats: { inputLines: source.split('\n').length, outputLines: 0, reduction: '0%', compileTime: performance.now() - startTime },
    };
  }

  // 4. Post-process output
  const inputLines = source.split('\n').filter(l => l.trim() && !l.trim().startsWith('//')).length;
  const outputLines = rawCode.split('\n').filter(l => l.trim() && !l.trim().startsWith('#')).length;
  const reduction = inputLines > 0
    ? `${Math.round((1 - outputLines / inputLines) * 100)}%`
    : '0%';

  // Build final Python code
  let finalCode = '';

  // Add header comment
  if (includeComments) {
    finalCode += `# ============================================================\n`;
    finalCode += `# Generated by NeuralLang Transpiler v0.8.2\n`;
    finalCode += `# Source: NeuralLang → Python / PyTorch\n`;
    finalCode += `# ============================================================\n\n`;
  }

  // Add imports
  if (includeImports) {
    finalCode += `import torch\n`;
    finalCode += `import torch.nn as nn\n`;
    finalCode += `import torch.nn.functional as F\n`;
    finalCode += `\n`;
  }

  finalCode += rawCode.trim();

  const compileTime = Math.round((performance.now() - startTime) * 100) / 100;

  return {
    success: true,
    python: finalCode.trim(),
    imports: ['torch', 'torch.nn', 'torch.nn.functional'],
    errors,
    warnings,
    stats: {
      inputLines,
      outputLines,
      reduction,
      compileTime,
    },
  };
}
