//! Code Generator: Transpile AI Language to PyTorch Python code
//! This is the MVP backend - generates executable Python/PyTorch code

use crate::ast::*;

pub struct CodeGenerator {
    indent_level: usize,
    use_torch_compile: bool,
}

impl CodeGenerator {
    pub fn new() -> Self {
        Self {
            indent_level: 0,
            use_torch_compile: true,
        }
    }

    /// Generate Python/PyTorch code from parsed program
    pub fn generate(&self, program: &[TopLevelDecl]) -> String {
        let mut code = String::new();

        // Header
        code.push_str("# Generated by AI Language Compiler\n");
        code.push_str("# Neural Syntax → PyTorch\n\n");
        code.push_str("import torch\n");
        code.push_str("import torch.nn as nn\n");
        code.push_str("from typing import Any\n\n");

        for decl in program {
            code.push_str(&self.generate_decl(decl));
            code.push('\n');
        }

        code
    }

    fn generate_decl(&self, decl: &TopLevelDecl) -> String {
        match decl {
            TopLevelDecl::Model(model) => self.generate_model(model),
            TopLevelDecl::Train(train) => self.generate_train(train),
            TopLevelDecl::Function(fn_def) => self.generate_function(fn_def),
            TopLevelDecl::TypeAlias(type_alias) => self.generate_type_alias(type_alias),
        }
    }

    fn generate_model(&self, model: &ModelDef) -> String {
        let mut code = String::new();

        code.push_str(&format!("class {}(nn.Module):\n", model.name));
        code.push_str(&self.indent());
        code.push_str("def __init__(self");
        // TODO: add constructor params
        code.push_str("):\n");
        code.push_str(&self.indent());
        code.push_str("super().__init__()\n\n");

        // Generate layers from flow body
        let layers = self.extract_layers_from_flow(&model.flow_body);
        for (i, (layer_name, layer_code)) in layers.iter().enumerate() {
            code.push_str(&self.indent());
            code.push_str(&format!("self.{} = {}\n", layer_name, layer_code));
        }

        code.push('\n');
        code.push_str(&self.indent());
        code.push_str("def forward(self, x):\n");

        // Generate forward pass from flow
        let forward = self.generate_forward_from_flow(&model.flow_body, "x");
        code.push_str(&forward);
        code.push('\n');

        code
    }

    fn extract_layers_from_flow(&self, expr: &AstNode<Expr>) -> Vec<(String, String)> {
        let mut layers = Vec::new();
        self.collect_layers(expr, &mut layers, 0);
        layers
    }

    fn collect_layers(&self, expr: &AstNode<Expr>, layers: &mut Vec<(String, String)>, idx: &mut usize) {
        match &expr.value {
            Expr::ArrowChain(steps) => {
                for step in steps {
                    self.collect_layers(step, layers, idx);
                }
            }
            Expr::LayerCall { name, args, post_ops } => {
                let py_code = self.layer_to_pytorch(name, args, post_ops);
                let var_name = format!("layer{}", idx);
                *idx += 1;
                layers.push((var_name.clone(), py_code));
            }
            Expr::Parallel(branches) => {
                for branch in branches {
                    self.collect_layers(branch, layers, idx);
                }
            }
            Expr::Repeat { body, .. } => {
                self.collect_layers(body, layers, idx);
            }
            Expr::Grouped(inner) => {
                self.collect_layers(inner, layers, idx);
            }
            Expr::Save { expr, .. } => {
                self.collect_layers(expr, layers, idx);
            }
            _ => {}
        }
    }

    fn layer_to_pytorch(&self, name: &str, args: &[(String, ArgValue)], post_ops: &[PostOp]) -> String {
        match name {
            "Conv2D" | "conv2d" | "Conv2d" => {
                let filters = args.iter().find(|(k, _)| k == "filters")
                    .and_then(|(_, v)| if let ArgValue::Number(n) = v { Some(*n as i64) } else { None })
                    .unwrap_or(64);
                let kernel = args.iter().find(|(k, _)| k == "kernel_size" || k == "kernel")
                    .map(|(_, v)| format!("{}", v))
                    .unwrap_or("3".into());

                let padding = if kernel.contains("3") { "1" } else { "0" };

                format!(
                    "nn.Conv2d({}, {}, kernel_size={}, padding={})",
                    3, // in_channels (would need type inference)
                    filters,
                    kernel,
                    padding
                )
            }
            "Linear" | "linear" | "Dense" | "dense" | "FC" | "fc" => {
                let out_features = args.iter().find(|(k, _)| k == "out_features" || k == "units")
                    .and_then(|(_, v)| if let ArgValue::Number(n) = v { Some(*n as i64) } else { None })
                    .unwrap_or(512);

                format!("nn.Linear({}, {})", "in_features_placeholder", out_features)
            }
            "BatchNorm" | "BN" | "bn" | "batchnorm" => {
                let num_features = args.iter().find(|(k, _)| k == "num_features" || k == "features")
                    .and_then(|(_, v)| if let ArgValue::Number(n) = v { Some(*n as i64) } else { None });

                match num_features {
                    Some(n) => format!("nn.BatchNorm2d({})", n),
                    None => "nn.BatchNorm2d(channel_placeholder)".into(),
                }
            }
            "ReLU" | "relu" => "nn.ReLU(inplace=True)".into(),
            "GELU" | "gelu" => "nn.GELU()".into(),
            "Sigmoid" | "sigmoid" => "nn.Sigmoid()".into(),
            "Softmax" | "softmax" => "nn.Softmax(dim=-1)".into(),
            "Dropout" | "dropout" => {
                let p = args.iter().find(|(k, _)| k == "p" || k == "rate")
                    .and_then(|(_, v)| if let ArgValue::Number(n) = v { Some(*n) } else { None })
                    .unwrap_or(0.5);
                format!("nn.Dropout({})", p)
            }
            "MaxPool" | "maxpool" | "MaxPool2d" => {
                let size = args.iter().find(|(k, _)| k == "size" || k == "kernel_size")
                    .map(|(_, v)| format!("{}", v))
                    .unwrap_or("2".into());
                format!("nn.MaxPool2d({})", size)
            }
            "AvgPool" | "avgpool" | "AvgPool2d" | "GlobalAvgPool" => {
                "nn.AdaptiveAvgPool2d((1, 1))".into()
            }
            "Flatten" | "flatten" => "nn.Flatten()".into(),
            "LayerNorm" | "layernorm" => {
                let eps = args.iter().find(|(k, _)| k == "eps")
                    .and_then(|(_, v)| if let ArgValue::Number(n) = v { Some(*n) } else { None })
                    .unwrap_or(1e-5);
                format!("nn.LayerNorm(normalized_shape, eps={})", eps)
            }
            "Attention" | "attention" | "MultiHeadAttention" => {
                let heads = args.iter().find(|(k, _)| k == "num_heads" || k == "heads")
                    .and_then(|(_, v)| if let ArgValue::Number(n) = v { Some(*n as i64) } else { None })
                    .unwrap_or(8);
                format!("nn.MultiheadAttention(embed_dim={}, num_heads={}, batch_first=True)", "embed_dim_placeholder", heads)
            }
            other => format!("# Custom layer: {}", other),
        }
    }

    fn generate_forward_from_flow(&self, expr: &AstNode<Expr>, input_var: &str) -> String {
        let mut code = String::new();
        self.gen_forward_expr(expr, input_var, &mut code, 0);
        code
    }

    fn gen_forward_expr(&self, expr: &AstNode<Expr>, current_var: &str, code: &mut mut String, layer_idx: &mut usize) {
        self.indent_level += 1;

        match &expr.value {
            Expr::ArrowChain(steps) => {
                let mut var = current_var.to_string();
                
                for (i, step) in steps.iter().enumerate() {
                    let next_var = if i == steps.len() - 1 {
                        "x".to_string()
                    } else {
                        format!("x_{}", i)
                    };

                    self.gen_forward_expr(step, &var, code, layer_idx);
                    var = next_var;
                }

                code.push_str(&self.indent());
                code.push_str(&format!("return {}\n", var));
            }

            Expr::LayerCall { name, args, post_ops } => {
                let layer_var = format!("layer{}", layer_idx);
                *layer_idx += 1;

                // Handle post-ops inline
                let mut ops_str = String::new();
                for post in post_ops {
                    ops_str.push_str(&format!(" + {}", self.postop_to_pytorch(post)));
                }

                code.push_str(&self.indent());
                code.push_str(&format!("{} = self.{}({}){}\n", current_var, layer_var, current_var, ops_str));
            }

            Expr::Parallel(branches) => {
                // Generate each branch
                for (i, branch) in branches.iter().enumerate() {
                    let branch_var = format!("{}_branch{}", current_var, i);
                    // Note: full parallel implementation would need torch.cat
                    self.gen_forward_expr(branch, current_var, code, layer_idx);
                }
                code.push_str(&self.indent());
                code.push_str(&format!("{} = torch.cat([{}], dim=1)\n", current_var, /* branch vars */ "_branch0"));
            }

            Expr::Repeat { body, count } => {
                match count {
                    RepeatCount::Literal(n) => {
                        code.push_str(&self.indent());
                        code.push_str(&format!("# Repeat block {} times\n", n));
                        // In practice, would generate Sequential with *n
                    }
                    RepeatCount::Dynamic(var) => {
                        code.push_str(&self.indent());
                        code.push_str(&format!("# Repeat {} times (dynamic)\n", var));
                    }
                    RepeatCount::Range(start, end) => {
                        code.push_str(&self.indent());
                        code.push_str(&format!("# Repeat {} to {} times\n", start, end));
                    }
                }
                self.gen_forward_expr(body, current_var, code, layer_idx);
            }

            Expr::Identifier(name) => {
                // Variable reference - no-op in forward
            }

            Expr::Grouped(inner) => {
                self.gen_forward_expr(inner, current_var, code, layer_idx);
            }

            Expr::Save { expr: inner, name } => {
                code.push_str(&self.indent());
                code.push_str(&format!("{}_{save} = {}.clone()\n", current_var, name, current_var));
                self.gen_forward_expr(inner, current_var, code, layer_idx);
            }

            Expr::Load(name) => {
                code.push_str(&self.indent());
                code.push_str(&format!("{} = {}_save\n", current_var, name));
            }

            Expr::BinaryOp { left, op, right } => {
                // Would need more complex handling
                code.push_str(&self.indent());
                code.push_str(&format!("# Binary op: {:?}\n", op));
            }

            other => {
                code.push_str(&self.indent());
                code.push_str(&format!("# TODO: Handle {:?}\n", other));
            }
        }

        self.indent_level -= 1;
    }

    fn postop_to_pytorch(&self, post: &PostOp) -> String {
        match post {
            PostOp::BatchNorm => "self.bn(x)".into(),
            PostOp::ReLU => "F.relu(x)".into(),
            PostOp::GELU => "F.gelu(x)".into(),
            PostOp::Sigmoid => "torch.sigmoid(x)".into(),
            PostOp::Softmax => "F.softmax(x, dim=-1)".into(),
            PostOp::Dropout(p) => format!("self.dropout(x)"), // would need actual dropout instance
            PostOp::MaxPool((h, w)) => format!("F.max_pool2d(x, {})".into(), format!("{}×{}", h, w)),
            PostOp::AvgPool((h, w)) => format!("F.avg_pool2d(x, {})".into(), format!("{}×{}", h, w)),
            PostOp::LayerNorm(eps) => format!("self.ln(x)").into(),
            PostOp::Custom(s) => format!("{}(x)", s),
        }
    }

    fn generate_train(&self, train: &TrainDef) -> String {
        let mut code = String::new();

        code.push_str(&format!("def train_{}():\n", train.model_name));
        code.push_str(&self.indent());
        code.push_str(&format!("model = {}()\n", train.model_name));
        code.push_str(&self.indent());
        code.push_str(&format!("criterion = nn.{}Loss()\n", train.config.loss_fn));
        code.push_str(&self.indent());
        code.push_str(&format!("optimizer = optim.{}(model.parameters(), lr={})\n", 
            train.config.optimizer, train.config.learning_rate));
        code.push('\n');
        code.push_str(&self.indent());
        code.push_str(&format!("for epoch in range({}):\n", train.config.epochs));
        code.push_str(&self.indent());
        code.push_str("    # Training loop here\n");
        code.push_str(&self.indent());
        code.push_str("    pass\n\n");

        code
    }

    fn generate_function(&self, fn_def: &FnDef) -> String {
        let ret = match &fn_def.return_type {
            Some(ty) => format!(" -> {}", self.type_to_python(ty)),
            None => String::new(),
        };

        let params_str: String = fn_def.params.iter()
            .map(|(name, ty)| format!("{}: {}", name, self.type_to_python(ty)))
            .collect::<Vec<_>>()
            .join(", ");

        format!("def {}({}){}:\n{}    pass\n\n", fn_def.name, params_str, ret, self.indent())
    }

    fn generate_type_alias(&self, type_alias: &TypeAliasDef) -> String {
        format!("{} = {}\n\n", type_alias.name, self.type_to_python(&type_alias.alias))
    }

    fn type_to_python(&self, ty: &TensorType) -> String {
        match ty {
            TensorType::Static { shape, dtype } => {
                let dims: Vec<String> = shape.iter().map(|d| match d {
                    Dimension::Literal(n) => n.to_string(),
                    Dimension::Symbol(s) => s.clone(),
                    Dimension::Infer => "...".into(),
                }).collect();
                format!("torch.Tensor[{}]", dims.join(", "))
            }
            TensorType::Symbolic { symbols, .. } => {
                format!("torch.Tensor[{}]", symbols.join(", "))
            }
            TensorType::Named { base, dims } => {
                let dims_str: Vec<String> = dims.iter().map(|(name, val)| {
                    match val {
                        Some(Dimension::Literal(n)) => format!("{}={}", name, n),
                        Some(Dimension::Symbol(s)) => format!("{}={}", name, s),
                        _ => name.clone(),
                    }
                }).collect();
                format!("{}[{}]", base, dims_str.join(", "))
            }
            TensorType::TypeVar(s) => s.clone(),
        }
    }

    fn indent(&self) -> String {
        "    ".repeat(self.indent_level)
    }
}
